package ts

// header is the banner stamped on top of every generated .ts file.
// Make it noisy enough that no developer mistakes the output for
// hand-written code. The schema-version comment is filled in by the
// _meta.json — we don't want to embed a hash here too because then
// every .ts file's mtime jumps on every regen and review noise wins.
const header = `// Code generated by railbase generate sdk — DO NOT EDIT.
//
// Re-run ` + "`railbase generate sdk`" + ` after schema changes. See _meta.json
// for the schemaHash; the SDK warns when it drifts from the server.

`
