package files

import (
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// FSDriver writes blobs to a local directory. Used in dev + single-node
// deploys; S3 / GCS drivers swap in for multi-replica setups.
//
// Layout: `<Root>/<key>` where `key` is the content-addressed path
// produced by StorageKey(). Atomicity: writes go to `<path>.tmp` then
// `os.Rename` — readers never see a half-written file.
type FSDriver struct {
	// Root is the absolute path to the storage directory. Created on
	// demand (lazy) the first time Put runs — call NewFSDriver to
	// validate up front.
	Root string
}

// NewFSDriver constructs a driver rooted at `root`. The directory is
// created (MkdirAll) so callers don't have to.
func NewFSDriver(root string) (*FSDriver, error) {
	if root == "" {
		return nil, errors.New("files: FSDriver Root required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		return nil, err
	}
	return &FSDriver{Root: abs}, nil
}

// resolvePath produces the absolute on-disk path for a storage key,
// rejecting traversal attempts. The key was generated by SanitiseFilename
// + content hash, so this is belt-and-braces defence.
func (d *FSDriver) resolvePath(key string) (string, error) {
	if strings.Contains(key, "..") {
		return "", errors.New("files: key may not contain '..'")
	}
	if filepath.IsAbs(key) {
		return "", errors.New("files: key must be relative")
	}
	full := filepath.Join(d.Root, filepath.FromSlash(key))
	// After Join, full must still be inside Root. If a key like
	// `foo/../../etc/passwd` slipped through the ".." check (it
	// wouldn't, but defense in depth), this catches it.
	if !strings.HasPrefix(full+string(filepath.Separator), d.Root+string(filepath.Separator)) {
		return "", errors.New("files: key escapes storage root")
	}
	return full, nil
}

// Put streams body to a temp file under Root, then renames into place.
// Returns bytes written. Caller is responsible for closing body.
func (d *FSDriver) Put(ctx context.Context, key string, body io.Reader) (int64, error) {
	full, err := d.resolvePath(key)
	if err != nil {
		return 0, err
	}
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return 0, err
	}
	tmp := full + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return 0, err
	}
	// Honour ctx via a wrapped reader so a hung upload terminates.
	rr := &ctxReader{ctx: ctx, r: body}
	n, copyErr := io.Copy(f, rr)
	closeErr := f.Close()
	if copyErr != nil {
		_ = os.Remove(tmp)
		return n, copyErr
	}
	if closeErr != nil {
		_ = os.Remove(tmp)
		return n, closeErr
	}
	if err := os.Rename(tmp, full); err != nil {
		_ = os.Remove(tmp)
		return n, err
	}
	return n, nil
}

// Open returns a *os.File satisfying ReadSeekCloser. http.ServeContent
// uses Seek for range requests.
func (d *FSDriver) Open(ctx context.Context, key string) (ReadSeekCloser, error) {
	full, err := d.resolvePath(key)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(full)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return f, nil
}

// Delete removes the file at key. Idempotent — missing key = nil.
func (d *FSDriver) Delete(ctx context.Context, key string) error {
	full, err := d.resolvePath(key)
	if err != nil {
		return err
	}
	if err := os.Remove(full); err != nil && !os.IsNotExist(err) {
		return err
	}
	// Best-effort prune of the two parent directories (the sha256
	// fan-out folders). If non-empty the RemoveAll-style call would
	// be wrong; we attempt Remove which only succeeds on empty dirs.
	parent := filepath.Dir(full)
	_ = os.Remove(parent)
	_ = os.Remove(filepath.Dir(parent))
	return nil
}

// ctxReader honours ctx.Done() between io.Copy reads. Without this,
// a slow upload could outlive a cancelled request.
type ctxReader struct {
	ctx context.Context
	r   io.Reader
}

func (c *ctxReader) Read(p []byte) (int, error) {
	select {
	case <-c.ctx.Done():
		return 0, c.ctx.Err()
	default:
	}
	return c.r.Read(p)
}
