package pbimport

import "text/template"

// outputTemplate renders a Go source file from a translated collection
// list. The file imports the Railbase schema package and registers
// each collection in an `init()` function. Operators drop the file
// into their project, `import _ "..."` from main, and the registry
// picks them up at boot.
//
// Why text/template (not go/printer): the output is a small Go file
// with deterministic structure; printf-friendly templating is enough
// and keeps the implementation visible. If we ever need AST-level
// manipulation we'd switch.
var outputTemplate = template.Must(template.New("pb-import").
	Funcs(template.FuncMap{
		"derefString":      derefString,
		"goStringLit":      goStringLit,
	}).
	Parse(`// Code generated by railbase import schema --from-pb. DO NOT EDIT.
// Source: {{.Source}}
// Generated: {{.GeneratedAt}}
//
// Translation caveats:
//   - PB filter syntax mostly matches Railbase, but @collection.X
//     references aren't supported yet — check the rules below.
//   - PB's "view" collections are skipped (Railbase v1 doesn't ship views).
//   - System collections (_admins / _otps / _externalAuths / _mfas /
//     _authOrigins) are skipped — Railbase wires equivalents via
//     system migrations.

package {{.Package}}

import "github.com/railbase/railbase/pkg/railbase/schema"

func init() {
{{- range .Collections}}
{{if .Skipped}}
	// SKIPPED: {{.Name}} — {{.Skipped}}
{{else}}
	schema.Register(
		schema.{{if .IsAuth}}AuthCollection{{else}}Collection{{end}}({{.Name | goStringLit}}).
		{{- range .Fields}}
			Add({{.Name | goStringLit}}, {{.Type}}){{.CallChain}}.
		{{- end}}
		{{- with .Rules.List}}
			ListRule({{. | goStringLit}}). // TODO: verify PB filter syntax
		{{- end}}
		{{- with .Rules.View}}
			ViewRule({{. | goStringLit}}). // TODO: verify PB filter syntax
		{{- end}}
		{{- with .Rules.Create}}
			CreateRule({{. | goStringLit}}). // TODO: verify PB filter syntax
		{{- end}}
		{{- with .Rules.Update}}
			UpdateRule({{. | goStringLit}}). // TODO: verify PB filter syntax
		{{- end}}
		{{- with .Rules.Delete}}
			DeleteRule({{. | goStringLit}}). // TODO: verify PB filter syntax
		{{- end}}
		{{- if .IsAuth}}
			// PB auth options
			{{- if .AuthOpts.RequireEmail}}
			// TODO: PB .requireEmail = true (Railbase equivalent: AuthCollection makes Email required by default)
			{{- end}}
			{{- if gt .AuthOpts.MinPasswordLength 0}}
			// TODO: PB .minPasswordLength = {{.AuthOpts.MinPasswordLength}} (configure via settings.password.min_length)
			{{- end}}
			{{- if .AuthOpts.OnlyVerified}}
			// TODO: PB .onlyVerified = true (Railbase: enforce in CreateRule/UpdateRule)
			{{- end}}
		{{- end}}
	)
{{end}}
{{- end}}
}
`))

// derefString returns "" for nil *string, else *s. Helps the template
// branch over optional rules without falling into go/template's
// quirky-around-nil-pointer behaviour.
func derefString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// goStringLit renders s as a Go string literal — uses %q so embedded
// quotes / newlines / non-ASCII bytes round-trip safely. PB rules
// often contain `"` characters; %q escapes them as \" which is what
// gofmt would produce.
func goStringLit(s string) string {
	return goQuote(s)
}

// goQuote is %q-equivalent. We use fmt.Sprintf("%q", s) elsewhere;
// this helper exists so the template's pipe syntax (`. | goStringLit`)
// stays readable.
func goQuote(s string) string {
	// Reuse the standard library's quoter.
	return string(quotedBytes(s))
}

func quotedBytes(s string) []byte {
	out := make([]byte, 0, len(s)+2)
	out = append(out, '"')
	for _, r := range s {
		switch r {
		case '\\':
			out = append(out, '\\', '\\')
		case '"':
			out = append(out, '\\', '"')
		case '\n':
			out = append(out, '\\', 'n')
		case '\r':
			out = append(out, '\\', 'r')
		case '\t':
			out = append(out, '\\', 't')
		default:
			if r < 0x20 {
				out = append(out, []byte{'\\', 'x', hex(byte(r>>4)), hex(byte(r&0xf))}...)
			} else {
				// Use Go-string encoding via append-rune
				var buf [4]byte
				n := encodeRune(buf[:], r)
				out = append(out, buf[:n]...)
			}
		}
	}
	out = append(out, '"')
	return out
}

func hex(b byte) byte {
	if b < 10 {
		return '0' + b
	}
	return 'a' + (b - 10)
}

// encodeRune wraps utf8.EncodeRune so the import stays minimal here.
// Kept local to avoid an unused-import lint if other parts of the
// package change.
func encodeRune(p []byte, r rune) int {
	// We can use utf8 indirectly via string conversion — cleaner.
	s := string(r)
	return copy(p, s)
}
